export interface QuestionItem {
  id: string;
  type: 'matching' | 'translation' | 'listening' | 'speaking' | 'imageChoice'; 
  description: string;
  sentence: string;
  correctAnswer: string;
  options: string[];  // Cevap seçenekleri
  x: number;
  y: number;
  unit?: number;

  extra?: boolean; // ← bu satırı ekle
  
  // Sadece matching için alanlar
  leftOptions?: string[];
  rightOptions?: string[];
  correctPairs?: { left: string, right: string }[];

  words?: string[];
  

  // Görsel sorular için opsiyonel alan
  images?: { label: string; image: any }[];
}

export const questions: QuestionItem[] = [
  {
    id: 'q1',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Hoşça kal"',
    sentence: 'Hoşça kal',
    correctAnswer: 'Goodbye',
    options: ['Hello', 'Goodbye', 'Thank you', 'Sorry'],
    unit: 1,
    x: 100,
    y: 130,
  },
  {
    id: 'q2',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Nasılsın?"',
    sentence: 'Nasılsın?',
    correctAnswer: 'How are you?',
    options: ['Who are you?', 'How are you?', 'Where are you?', 'I am fine'],
    unit: 1,
    x: 200,
    y: 230,
  },
  {
    id: 'q3',
    type: 'matching',
    description: 'Türkçe ve İngilizce eşleştir 1',
    sentence: 'Example sentence for matching 1',
    correctAnswer: 'Example answer 1',
    options: ['Example answer 1', 'Example answer 2', 'Example answer 3', 'Example answer 4'],
    leftOptions: ['İnglizce', 'Merhaba', 'Teşekkürler'],
    rightOptions: ['English', 'Hello', 'Thanks'],
    correctPairs: [
      { left: 'İnglizce', right: 'English' },
      { left: 'Merhaba', right: 'Hello' },
      { left: 'Teşekkürler', right: 'Thanks' },
    ],
    unit: 1,
    x: 100,
    y: 330,
  },
  {
    id: 'q4',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Neredesin?"',
    sentence: 'Neredesin?',
    correctAnswer: 'Where are you?',
    options: ['Where are you?', 'Who are you?', 'I am fine', 'How are you?'],
    unit: 1,
    x: 200,
    y: 430,
  },
  {
    id: 'q5',
    type: 'matching',
    description: 'Türkçe ve İngilizce eşleştir 2',
    sentence: 'Example sentence for matching 2',
    correctAnswer: 'Example answer 2',
    options: ['Example answer 1', 'Example answer 2', 'Example answer 3', 'Example answer 4'],
    leftOptions: ['Elma', 'Kitap', 'Masa'],
    rightOptions: ['Apple', 'Book', 'Table'],
    correctPairs: [
      { left: 'Elma', right: 'Apple' },
      { left: 'Kitap', right: 'Book' },
      { left: 'Masa', right: 'Table' },
    ],
    unit: 1,
    x: 100,
    y: 530,
  },
  {
    id: 'q6',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Ben okula gidiyorum."',
    sentence: 'Ben okula gidiyorum.',
    correctAnswer: 'I am going to school.',
    options: ['I am going to school.', 'I am eating apple.', 'I am reading a book.'],
    unit: 1,
    x: 200,
    y: 630,
  },
  {
    id: 'q7',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Bu bir elma."',
    sentence: 'Bu bir elma.',
    correctAnswer: 'This is an apple.',
    options: ['This is a banana.', 'This is an apple.', 'This is a book.'],
    unit: 1,
    x: 100,
    y: 730,
  },
  {
    id: 'q8',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Merhaba."',
    sentence: 'Merhaba.',
    correctAnswer: 'Hello',
    options: ['Hello', 'Hi', 'Goodbye'],
    unit: 1,
    x: 200,
    y: 830,
  },
  {
    id: 'q9',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Teşekkür ederim"',
    sentence: 'Teşekkür ederim',
    correctAnswer: 'Thank you',
    options: ['Sorry', 'Hello', 'Thank you', 'Goodbye'],
    unit: 1,
    x: 100,
    y: 930,
  },
  {
    id: 'q10',
    type: 'matching',
    description: 'Türkçe ve İngilizce eşleştir 3',
    sentence: 'Example sentence for matching 3',
    correctAnswer: 'Example answer 3',
    options: ['Example answer 1', 'Example answer 2', 'Example answer 3', 'Example answer 4'],
    leftOptions: ['Günaydın', 'İyi akşamlar', 'Merhaba'],
    rightOptions: ['Good morning', 'Good evening', 'Hello'],
    correctPairs: [
      { left: 'Günaydın', right: 'Good morning' },
      { left: 'İyi akşamlar', right: 'Good evening' },
      { left: 'Merhaba', right: 'Hello' },
    ],
    unit: 1,
    x: 200,
    y: 1030,
  },
  {
    id: 'q11',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'I am eating an apple.',
    correctAnswer: 'I am eating an apple.',
    options: [], // Artık kullanılmıyor, istersen tamamen kaldırabilirsin
    words: ['I', 'am', 'eating', 'an', 'apple', 'banana', 'like'],
    unit: 1,
    x: 100,
    y: 1130,
  },
  {
    id: 'q12',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'She is reading a book.',
    correctAnswer: 'She is reading a book.',
    options: [],
    words: ['She', 'is', 'reading', 'a', 'book', 'they', 'runs'],
    unit: 1,
    x: 200,
    y: 1230,
  },
  {
    id: 'q13',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'This is my cat.',
    correctAnswer: 'This is my cat.',
    options: [],
    words: ['This', 'is', 'my', 'cat', 'dog', 'like'],
    unit: 1,
    x: 100,
    y: 1330,
  },
  {
    id: 'q14',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'We are going to the park.',
    correctAnswer: 'We are going to the park.',
    options: [],
    words: ['We', 'are', 'going', 'to', 'the', 'park', 'store', 'they'],
    unit: 1,
    x: 200,
    y: 1430,
  },
  {
    id: 'q15',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'They are playing football.',
    correctAnswer: 'They are playing football.',
    options: [],
    words: ['They', 'are', 'playing', 'football', 'tennis', 'like'],
    unit: 1,
    x: 100,
    y: 1530,
  },
  {
    id: 'q16',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "Hello, how are you?"',
    sentence: 'Hello, how are you?',
    correctAnswer: 'Hello, how are you?',
    options: [],
    unit: 1,
    x: 200,
    y: 1630,
  },
  {
    id: 'q17',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "Your snake is very smart!"',
    sentence: 'Your snake is very smart!',
    correctAnswer: 'Your snake is very smart!',
    options: [],
    unit: 1,
    x: 100,
    y: 1730,
  },
  {
    id: 'q18',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "I love reading books."',
    sentence: 'I love reading books.',
    correctAnswer: 'I love reading books.',
    options: [],
    unit: 1,
    x: 200,
    y: 1830,
  },
  {
    id: 'q19',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "We are going to the cinema."',
    sentence: 'We are going to the cinema.',
    correctAnswer: 'We are going to the cinema.',
    options: [],
    unit: 1,
    x: 100,
    y: 1930,
  },
  {
    id: 'q20',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "They are playing football together."',
    sentence: 'They are playing football together.',
    correctAnswer: 'They are playing football together.',
    options: [],
    unit: 1,
    x: 200,
    y: 2030,
  },
  {
    id: 'q21',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "şeker"',
    sentence: 'Sugar',
    correctAnswer: 'şeker',
    options: [],
    x: 100,
    y: 2130,
    images: [
      { label: 'şeker', image: require('./assets/images/sugar.png') }, // Doğru cevap
      { label: 'süt', image: require('./assets/images/milk.png') },
      { label: 'çay', image: require('./assets/images/tea.png') },
      { label: 'kahve', image: require('./assets/images/coffee.png') },
    ],
    unit: 1,
  },
  {
    id: 'q22',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "su"',
    sentence: 'Water',
    correctAnswer: 'su',
    options: [],
    x: 200,
    y: 2230,
    images: [
      { label: 'su', image: require('./assets/images/water.png') },   // Doğru cevap
      { label: 'çay', image: require('./assets/images/tea.png') },
      { label: 'kahve', image: require('./assets/images/coffee.png') },
      { label: 'şeker', image: require('./assets/images/sugar.png') },
    ],
    unit: 1,
  },
  {
    id: 'q23',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "süt"',
    sentence: 'Milk',
    correctAnswer: 'süt',
    options: [],
    x: 100,
    y: 2330,
    images: [
      { label: 'süt', image: require('./assets/images/milk.png') },   // Doğru cevap
      { label: 'su', image: require('./assets/images/water.png') },
      { label: 'kahve', image: require('./assets/images/coffee.png') },
      { label: 'çay', image: require('./assets/images/tea.png') },
    ],
    unit: 1,
  },
  {
    id: 'q24',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "çay"',
    sentence: 'Tea',
    correctAnswer: 'çay',
    options: [],
    x: 200,
    y: 2430,
    images: [
      { label: 'çay', image: require('./assets/images/tea.png') },    // Doğru cevap
      { label: 'su', image: require('./assets/images/water.png') },
      { label: 'süt', image: require('./assets/images/milk.png') },
      { label: 'kahve', image: require('./assets/images/coffee.png') },
    ],
    unit: 1,
  },
  {
    id: 'q25',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "kahve"',
    sentence: 'Coffee',
    correctAnswer: 'kahve',
    options: [],
    x: 100,
    y: 2530,
    images: [
      { label: 'kahve', image: require('./assets/images/coffee.png') }, // Doğru cevap
      { label: 'su', image: require('./assets/images/water.png') },
      { label: 'çay', image: require('./assets/images/tea.png') },
      { label: 'süt', image: require('./assets/images/milk.png') },
    ],
    unit: 1,
  },

  // Matching (eşleştirme)
// Extra Matching
// Extra Matching
{
  id: 'q1e1',
  type: 'matching',
  description: 'İngilizce içecek kelimelerini Türkçeleriyle eşleştir.',
  sentence: 'Eşleştirme yapınız',
  correctAnswer: '',
  options: [],
  leftOptions: ['Su', 'Çay', 'Kahve', 'Süt'],
  rightOptions: ['Water', 'Tea', 'Coffee', 'Milk'],
  correctPairs: [
    { left: 'Su', right: 'Water' },
    { left: 'Çay', right: 'Tea' },
    { left: 'Kahve', right: 'Coffee' },
    { left: 'Süt', right: 'Milk' },
  ],
  x: 200,
  y: 2630,
  unit: 1,
  extra: true,
},

// Extra Translation
{
  id: 'q1e2',
  type: 'translation',
  description: 'Aşağıdaki kelimenin İngilizcesini seçin: Süt',
  sentence: 'Süt',
  correctAnswer: 'Milk',
  options: ['Milk', 'Tea', 'Water', 'Coffee'],
  x: 100,
  y: 2730,
  unit: 1,
  extra: true,
},

// Extra Listening
{
  id: 'q1e3',
  type: 'listening',
  description: 'Dinleyin ve doğru kelimeyi seçin',
  sentence: 'Water',
  correctAnswer: 'Water',
  options: [],
  words: ['Milk', 'Tea', 'Water', 'Coffee', 'Juice'],
  unit: 1,
  x: 200,
  y: 2830,
  extra: true,
},
// Extra Speaking
{
  id: 'q1e4',
  type: 'speaking',
  description: 'Aşağıdaki cümleyi yüksek sesle söyleyin.',
  sentence: 'I like drinking tea.',
  correctAnswer: 'I like drinking tea.',
  options: [],
  x: 100,
  y: 2930,
  unit: 1,
  extra: true,
},

// Extra ImageChoice
{
  id: 'q1e5',
  type: 'imageChoice',
  description: 'Doğru görseli seçin: "kahve"',
  sentence: 'Coffee',
  correctAnswer: 'kahve',
  options: [],
  x: 200,
  y: 3030,
  images: [
    { label: 'kahve', image: require('./assets/images/coffee.png') },
    { label: 'su', image: require('./assets/images/water.png') },
    { label: 'çay', image: require('./assets/images/tea.png') },
    { label: 'süt', image: require('./assets/images/milk.png') },
  ],
  unit: 1,
  extra: true,
},



// ----------------------------
  // 1) TRANSLATION (5 adet)
  // ----------------------------
  {
    id: 'q26',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Ben Türkiyeliyim"',
    sentence: 'Ben Türkiyeliyim',
    correctAnswer: 'I am from Turkey',
    options: ['I am from Turkey', 'I am from Mexico', 'I am from China', 'I am from Japan'],
    x: 100,
    y: 50,
    unit: 2,
  },
  {
    id: 'q27',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Nerelisin?"',
    sentence: 'Nerelisin?',
    correctAnswer: 'Where are you from?',
    options: ['Where are you from?', 'What is your name?', 'How are you?', 'Where do you live?'],
    x: 200,
    y: 150,
    unit: 2,
  },
  {
    id: 'q28',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "O Çinli"',
    sentence: 'O Çinli',
    correctAnswer: 'He is from China',
    options: ['He is from China', 'He is from Japan', 'He is from Turkey', 'He is from Brazil'],
    x: 100,
    y: 250,
    unit: 2,
  },
  {
    id: 'q29',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Onlar Japon"',
    sentence: 'Onlar Japon',
    correctAnswer: 'They are from Japan',
    options: ['They are from Japan', 'They are from Turkey', 'They are from China', 'They are from Mexico'],
    x: 200,
    y: 350,
    unit: 2,
  },
  {
    id: 'q30',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Ben Brezilyalıyım, ya sen?"',
    sentence: 'Ben Brezilyalıyım, ya sen?',
    correctAnswer: 'I am from Brazil, and you?',
    options: [
      'I am from Brazil, and you?',
      'I am from China, and you?',
      'I am from Japan, and you?',
      'I am from Mexico, and you?',
    ],
    x: 100,
    y: 450,
    unit: 2,
  },
  

  // ----------------------------
  // 2) MATCHING (5 adet)
  // ----------------------------
  {
    id: 'q31',
    type: 'matching',
    description: 'Ülkeleri eşleştirin 1',
    sentence: 'Match the countries (1)',
    correctAnswer: 'Example answer matching 1',
    options: [],
    x: 200,
    y: 550,
    unit: 2,
    leftOptions: ['Japonya', 'Meksika'],
    rightOptions: ['Japan', 'Mexico'],
    correctPairs: [
      { left: 'Japonya', right: 'Japan' },
      { left: 'Meksika', right: 'Mexico' },
    ],
  },
  {
    id: 'q32',
    type: 'matching',
    description: 'Ülkeleri eşleştirin 2',
    sentence: 'Match the countries (2)',
    correctAnswer: 'Example answer matching 2',
    options: [],
    x: 100,
    y: 650,
    unit: 2,
    leftOptions: ['Çin', 'Japonya'],
    rightOptions: ['China', 'Japan'],
    correctPairs: [
      { left: 'Çin', right: 'China' },
      { left: 'Japonya', right: 'Japan' },
    ],
  },
  {
    id: 'q33',
    type: 'matching',
    description: 'Ülkeleri eşleştirin 3',
    sentence: 'Match the countries (3)',
    correctAnswer: 'Example answer matching 3',
    options: [],
    x: 200,
    y: 750,
    unit: 2,
    leftOptions: ['Brezilya', 'Fransa'],
    rightOptions: ['Brazil', 'France'],
    correctPairs: [
      { left: 'Brezilya', right: 'Brazil' },
      { left: 'Fransa', right: 'France' },
    ],
  },
  {
    id: 'q34',
    type: 'matching',
    description: 'Ülkeleri eşleştirin 4',
    sentence: 'Match the countries (4)',
    correctAnswer: 'Example answer matching 4',
    options: [],
    x: 100,
    y: 850,
    unit: 2,
    leftOptions: ['Londra', 'Meksika'],
    rightOptions: ['London', 'Mexico'],
    correctPairs: [
      { left: 'Londra', right: 'London' },
      { left: 'Meksika', right: 'Mexico' },
    ],
  },
  {
    id: 'q35',
    type: 'matching',
    description: 'Ülkeleri eşleştirin 5',
    sentence: 'Match the countries (5)',
    correctAnswer: 'Example answer matching 5',
    options: [],
    x: 200,
    y: 950,
    unit: 2,
    leftOptions: ['Türkiye', 'Brezilya'],
    rightOptions: ['Turkey', 'Brazil'],
    correctPairs: [
      { left: 'Türkiye', right: 'Turkey' },
      { left: 'Brezilya', right: 'Brazil' },
    ],
  },

  // ----------------------------
  // 3) LISTENING (5 adet)
  // ----------------------------
  {
    id: 'q36',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'I am from Turkey',
    correctAnswer: 'I am from Turkey',
    options: [],
    words: ['I', 'am', 'from', 'Turkey', 'Japan', 'like'],
    x: 100,
    y: 1050,
    unit: 2,
  },
  {
    id: 'q37',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'He is from Japan',
    correctAnswer: 'He is from Japan',
    options: [],
    words: ['He', 'is', 'from', 'Japan', 'Brazil', 'we'],
    x: 200,
    y: 1150,
    unit: 2,
  },
  {
    id: 'q38',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'They are from China',
    correctAnswer: 'They are from China',
    options: [],
    words: ['They', 'are', 'from', 'China', 'Turkey', 'like'],
    x: 100,
    y: 1250,
    unit: 2,
  },
  {
    id: 'q39',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'I am from Brazil, and you?',
    correctAnswer: 'I am from Brazil, and you?',
    options: [],
    words: ['I', 'am', 'from', 'Brazil', 'and', 'you', 'Japan', 'where'],
    x: 200,
    y: 1350,
    unit: 2,
  },
  {
    id: 'q40',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'We are from France',
    correctAnswer: 'We are from France',
    options: [],
    words: ['We', 'are', 'from', 'France', 'Brazil', 'like'],
    x: 100,
    y: 1450,
    unit: 2,
  },

  // ----------------------------
  // 4) SPEAKING (5 adet)
  // ----------------------------
  {
    id: 'q41',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "I am from London."',
    sentence: 'I am from London.',
    correctAnswer: 'I am from London.',
    options: [],
    x: 200,
    y: 1550,
    unit: 2,
  },
  {
    id: 'q42',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "I am from Japan too."',
    sentence: 'I am from Japan too.',
    correctAnswer: 'I am from Japan too.',
    options: [],
    x: 100,
    y: 1650,
    unit: 2,
  },
  {
    id: 'q43',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "I am from Turkey, how about you?"',
    sentence: 'I am from Turkey, how about you?',
    correctAnswer: 'I am from Turkey, how about you?',
    options: [],
    x: 200,
    y: 1750,
    unit: 2,
  },
  {
    id: 'q44',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "We are from Mexico."',
    sentence: 'We are from Mexico.',
    correctAnswer: 'We are from Mexico.',
    options: [],
    x: 100,
    y: 1850,
    unit: 2,
  },
  {
    id: 'q45',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "He is from China."',
    sentence: 'He is from China.',
    correctAnswer: 'He is from China.',
    options: [],
    x: 200,
    y: 1950,
    unit: 2,
  },

  // ----------------------------
  // 5) IMAGE CHOICE (5 adet)
  // ----------------------------
  {
    id: 'q46',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "Türkiye"',
    sentence: 'Turkey',
    correctAnswer: 'Türkiye',
    options: [],
    x: 100,
    y: 2050,
    unit: 2,
    images: [
      { label: 'Türkiye', image: require('./assets/images/turkey.png') }, // Doğru
      { label: 'Meksika', image: require('./assets/images/mexico.png') },
      { label: 'Fransa', image: require('./assets/images/france.png') },
      { label: 'Çin', image: require('./assets/images/china.png') },
    ],
  },
  {
    id: 'q47',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "Meksika"',
    sentence: 'Mexico',
    correctAnswer: 'Meksika',
    options: [],
    x: 200,
    y: 2150,
    unit: 2,
    images: [
      { label: 'Meksika', image: require('./assets/images/mexico.png') }, // Doğru
      { label: 'Türkiye', image: require('./assets/images/turkey.png') },
      { label: 'Japonya', image: require('./assets/images/japan.png') },
      { label: 'Fransa', image: require('./assets/images/france.png') },
    ],
  },
  {
    id: 'q48',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "Japonya"',
    sentence: 'Japan',
    correctAnswer: 'Japonya',
    options: [],
    x: 100,
    y: 2250,
    unit: 2,
    images: [
      { label: 'Japonya', image: require('./assets/images/japan.png') }, // Doğru
      { label: 'Brezilya', image: require('./assets/images/brazil.png') },
      { label: 'Çin', image: require('./assets/images/china.png') },
      { label: 'Meksika', image: require('./assets/images/mexico.png') },
    ],
  },
  {
    id: 'q49',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "Fransa"',
    sentence: 'France',
    correctAnswer: 'Fransa',
    options: [],
    x: 200,
    y: 2350,
    unit: 2,
    images: [
      { label: 'Fransa', image: require('./assets/images/france.png') }, // Doğru
      { label: 'Japonya', image: require('./assets/images/japan.png') },
      { label: 'Türkiye', image: require('./assets/images/turkey.png') },
      { label: 'Brezilya', image: require('./assets/images/brazil.png') },
    ],
  },
  {
    id: 'q50',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "Çin"',
    sentence: 'China',
    correctAnswer: 'Çin',
    options: [],
    x: 100,
    y: 2450,
    unit: 2,
    images: [
      { label: 'Çin', image: require('./assets/images/china.png') }, // Doğru
      { label: 'Fransa', image: require('./assets/images/france.png') },
      { label: 'Meksika', image: require('./assets/images/mexico.png') },
      { label: 'Türkiye', image: require('./assets/images/turkey.png') },
    ],
  },

  {
    id: 'q2e1',
    type: 'translation',
    description: 'Cümleyi İngilizceye çevirin: Ben Almanya’danım.',
    sentence: 'Ben Almanya’danım.',
    correctAnswer: 'I am from Germany.',
    options: ['I am from Germany.', 'He is from Germany.', 'I am from France.', 'She is from Spain.'],
    x: 200,
    y: 2550,
    unit: 2,
    extra: true,
  },
  {
    id: 'q2e2',
    type: 'matching',
    description: 'Eşleştirme: Ülkeler ve dilleri eşleştir.',
    sentence: 'Ülkeler ve diller',
    correctAnswer: '',
    options: [],
    leftOptions: ['Germany', 'France', 'Italy', 'Spain'],
    rightOptions: ['German', 'French', 'Italian', 'Spanish'],
    correctPairs: [
      { left: 'Germany', right: 'German' },
      { left: 'France', right: 'French' },
      { left: 'Italy', right: 'Italian' },
      { left: 'Spain', right: 'Spanish' },
    ],
    x: 100,
    y: 2650,
    unit: 2,
    extra: true,
  },
  {
    id: 'q2e3',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun.',
    sentence: 'She is from France.',
    correctAnswer: 'She is from France.',
    options: [],
    words: ['She', 'is', 'from', 'France', 'Spain', 'Germany', 'Italy'],
    x: 200,
    y: 2750,
    unit: 2,
    extra: true,
  },
  {
    id: 'q2e4',
    type: 'speaking',
    description: 'Aşağıdaki cümleyi yüksek sesle söyleyin.',
    sentence: 'I am from Turkey.',
    correctAnswer: 'I am from Turkey.',
    options: [],
    x: 100,
    y: 2850,
    unit: 2,
    extra: true,
  },
  {
    id: 'q2e5',
    type: 'imageChoice',
    description: 'Doğru ülkeyi temsil eden bayrağı seçin: "Germany"',
    sentence: 'Germany',
    correctAnswer: 'Almanya',
    options: [],
    images: [
      { label: 'Almanya', image: require('./assets/images/germany.png') },
      { label: 'Fransa', image: require('./assets/images/france.png') },
      { label: 'İspanya', image: require('./assets/images/spain.png') },
      { label: 'İtalya', image: require('./assets/images/italy.png') },
    ],
    x: 200,
    y: 2950,
    unit: 2,
    extra: true,
  },
  
  {
    id: 'q51',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Selam, benim adım Lisa. Bu erkek kardeşim Tom."',
    sentence: 'Selam, benim adım Lisa. Bu erkek kardeşim Tom.',
    correctAnswer: 'Hi, my name is Lisa. This is my brother Tom.',
    options: ['Hi, my name is Lisa. This is my brother Tom.', 'Hello, I am Lisa. He is my sister Tom.', 'Hi, this is Lisa and Tom.', 'Goodbye, Lisa and Tom.'],
    x: 100,
    y: 50,
    unit: 3,
  },
  {
    id: 'q52',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Bu benim ailem: annem, babam ve kız kardeşim."',
    sentence: 'Bu benim ailem: annem, babam ve kız kardeşim.',
    correctAnswer: 'This is my family: my mom, my dad and my sister.',
    options: ['This is my family: my mom, my dad and my sister.', 'My sister and I are a family.', 'This is your family.', 'Mom, dad, sister.'],
    x: 200,
    y: 150,
    unit: 3,
  },
  {
    id: 'q53',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Benim adım Mia. Bu benim kız kardeşim Anna."',
    sentence: 'Benim adım Mia. Bu benim kız kardeşim Anna.',
    correctAnswer: 'My name is Mia. This is my sister Anna.',
    options: ['My name is Mia. This is my sister Anna.', 'Her name is Mia. This is my sister.', 'I am Anna. This is Mia.', 'This is my family.'],
    x: 100,
    y: 250,
    unit: 3,
  },
  {
    id: 'q54',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Merhaba, ben Alex. Bu benim annem."',
    sentence: 'Merhaba, ben Alex. Bu benim annem.',
    correctAnswer: 'Hello, I am Alex. This is my mom.',
    options: ['Hello, I am Alex. This is my mom.', 'Hi, she is Alex.', 'This is Alex’s mother.', 'I am mom.'],
    x: 200,
    y: 350,
    unit: 3,
  },
  {
    id: 'q55',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Ben Brezilyalıyım ve bu da benim erkek kardeşim."',
    sentence: 'Ben Brezilyalıyım ve bu da benim erkek kardeşim.',
    correctAnswer: 'I am from Brazil and this is my brother.',
    options: ['I am from Brazil and this is my brother.', 'He is from Brazil.', 'We are from Brazil.', 'This is my friend.'],
    x: 100,
    y: 450,
    unit: 3,
  },
  {
    id: 'q56',
    type: 'matching',
    description: 'Aile üyelerini İngilizce karşılıklarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Anne', 'Baba', 'Kız kardeş', 'Erkek kardeş'],
    rightOptions: ['Mom', 'Dad', 'Sister', 'Brother'],
    correctPairs: [
      { left: 'Anne', right: 'Mom' },
      { left: 'Baba', right: 'Dad' },
      { left: 'Kız kardeş', right: 'Sister' },
      { left: 'Erkek kardeş', right: 'Brother' }
    ],
    x: 200,
    y: 550,
    unit: 3,
  },
  {
    id: 'q57',
    type: 'matching',
    description: 'Selamlaşma ifadelerini eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Selam', 'Merhaba', 'Hoşça kal', 'Nasılsın?'],
    rightOptions: ['Hi', 'Hello', 'Goodbye', 'How are you?'],
    correctPairs: [
      { left: 'Selam', right: 'Hi' },
      { left: 'Merhaba', right: 'Hello' },
      { left: 'Hoşça kal', right: 'Goodbye' },
      { left: 'Nasılsın?', right: 'How are you?' }
    ],
    x: 100,
    y: 650,
    unit: 3,
  },
  {
    id: 'q58',
    type: 'matching',
    description: 'Ülkeler ve milletleri eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Türkiye', 'Fransa', 'Brezilya', 'Japonya'],
    rightOptions: ['Turkish', 'French', 'Brazilian', 'Japanese'],
    correctPairs: [
      { left: 'Türkiye', right: 'Turkish' },
      { left: 'Fransa', right: 'French' },
      { left: 'Brezilya', right: 'Brazilian' },
      { left: 'Japonya', right: 'Japanese' }
    ],
    x: 200,
    y: 750,
    unit: 3,
  },
  {
    id: 'q59',
    type: 'matching',
    description: 'Türkçe kelimeleri İngilizce anlamlarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Erkek kardeş', 'Aile', 'Merhaba', 'Fransa'],
    rightOptions: ['Brother', 'Family', 'Hello', 'France'],
    correctPairs: [
      { left: 'Erkek kardeş', right: 'Brother' },
      { left: 'Aile', right: 'Family' },
      { left: 'Merhaba', right: 'Hello' },
      { left: 'Fransa', right: 'France' },
    ],
    x: 100,
    y: 850,
    unit: 3,
  },
  {
    id: 'q60',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'Hi, my name is Jack. I am from England.',
    correctAnswer: 'Hi, my name is Jack. I am from England.',
    options: [],
    words: ['Hi', 'my', 'name', 'is', 'Jack', 'I', 'am', 'from', 'England'],
    x: 200,
    y: 950,
    unit: 3,
  },
  {
    id: 'q61',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'This is my mom and dad.',
    correctAnswer: 'This is my mom and dad.',
    options: [],
    words: ['This', 'is', 'my', 'mom', 'and', 'dad', 'sister', 'he'],
    x: 100,
    y: 1050,
    unit: 3,
  },
  {
    id: 'q62',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'We are from Mexico.',
    correctAnswer: 'We are from Mexico.',
    options: [],
    words: ['We', 'are', 'from', 'Mexico', 'Brazil', 'Turkey'],
    x: 200,
    y: 1150,
    unit: 3,
  },
  {
    id: 'q63',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'My brother is from Japan.',
    correctAnswer: 'My brother is from Japan.',
    options: [],
    words: ['My', 'brother', 'is', 'from', 'Japan', 'France'],
    x: 100,
    y: 1250,
    unit: 3,
  },
  {
    id: 'q64',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'Hello, this is my family.',
    correctAnswer: 'Hello, this is my family.',
    options: [],
    words: ['Hello', 'this', 'is', 'my', 'family', 'friends', 'dad'],
    x: 200,
    y: 1350,
    unit: 3,
  },
  {
    id: 'q65',
    type: 'speaking',
    description: 'Bu cümleyi sesli okuyun:',
    sentence: 'Hi, I am David. I live in Turkey with my family.',
    correctAnswer: 'Hi, I am David. I live in Turkey with my family.',
    options: [],
    x: 100,
    y: 1450,
    unit: 3,
  },
  {
    id: 'q66',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: ',
    sentence: 'This is my sister. Her name is Anna.',
    correctAnswer: 'This is my sister. Her name is Anna.',
    options: [],
    x: 200,
    y: 1550,
    unit: 3,
  },
  {
    id: 'q67',
    type: 'speaking',
    description: 'Bu cümleyi okuyun:',
    sentence: 'My dad is from France, but my mom is from Mexico.',
    correctAnswer: 'My dad is from France, but my mom is from Mexico.',
    options: [],
    x: 100,
    y: 1650,
    unit: 3,
  },
  {
    id: 'q68',
    type: 'speaking',
    description: 'Bu cümleyi okuyun:',
    sentence: 'We are from different countries but we are a family.',
    correctAnswer: 'We are from different countries but we are a family.',
    options: [],
    x: 200,
    y: 1750,
    unit: 3,
  },
  {
    id: 'q69',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: ',
    sentence: 'My family is big. I have two brothers and one sister.',
    correctAnswer: 'My family is big. I have two brothers and one sister.',
    options: [],
    x: 100,
    y: 1850,
    unit: 3,
  },
  {
    id: 'q70',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "kız kardeş"',
    sentence: 'Sister',
    correctAnswer: 'kız kardeş',
    options: [],
    x: 200,
    y: 1950,
    unit: 3,
    images: [
      { label: 'kız kardeş', image: require('./assets/images/sister.png') }, // ✅ doğru
      { label: 'süt', image: require('./assets/images/milk.png') },          // ünite 1
      { label: 'Türkiye', image: require('./assets/images/turkey.png') },    // ünite 2
      { label: 'şeker', image: require('./assets/images/sugar.png') },       // ünite 1
    ],
  },
  {
    id: 'q71',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "baba"',
    sentence: 'Dad',
    correctAnswer: 'baba',
    options: [],
    x: 100,
    y: 2050,
    unit: 3,
    images: [
      { label: 'baba', image: require('./assets/images/dad.png') },           // ✅ doğru
      { label: 'çay', image: require('./assets/images/tea.png') },            // ünite 1
      { label: 'Japonya', image: require('./assets/images/japan.png') },      // ünite 2
      { label: 'kahve', image: require('./assets/images/coffee.png') },       // ünite 1
    ],
  },
  {
    id: 'q72',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "erkek kardeş"',
    sentence: 'Brother',
    correctAnswer: 'erkek kardeş',
    options: [],
    x: 200,
    y: 2150,
    unit: 3,
    images: [
      { label: 'erkek kardeş', image: require('./assets/images/brother.png') }, // ✅ doğru
      { label: 'Fransa', image: require('./assets/images/france.png') },        // ünite 2
      { label: 'su', image: require('./assets/images/water.png') },             // ünite 1
      { label: 'anne', image: require('./assets/images/mom.png') },             // aynı ünite ama doğru değil
    ],
  },
  
  {
    id: 'q73',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Benim erkek kardeşim Japonya’da yaşıyor."',
    sentence: 'Benim erkek kardeşim Japonya’da yaşıyor.',
    correctAnswer: 'My brother lives in Japan.',
    options: ['My brother lives in Japan.', 'My sister is from Japan.', 'I live in Japan.', 'Japan is my country.'],
    x: 100,
    y: 2250,
    unit: 3,
  },
  {
    id: 'q74',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'We live in Turkey with our parents.',
    correctAnswer: 'We live in Turkey with our parents.',
    options: [],
    words: ['We', 'live', 'in', 'Turkey', 'with', 'our', 'parents'],
    x: 200,
    y: 2350,
    unit: 3,
  },
  {
    id: 'q75',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "This is my sister. She is from Japan and speaks English."',
    sentence: 'This is my sister. She is from Japan and speaks English.',
    correctAnswer: 'This is my sister. She is from Japan and speaks English.',
    options: [],
    x: 100,
    y: 2450,
    unit: 3,
  },
  {
    id: 'q3e1',
    type: 'translation',
    description: 'Cümleyi çevir: "Merhaba, benim adım Olivia. Ben Almanya’danım ve büyük bir ailem var."',
    sentence: 'Merhaba, benim adım Olivia. Ben Almanya’danım ve büyük bir ailem var.',
    correctAnswer: 'Hello, my name is Olivia. I am from Germany and I have a big family.',
    options: [
      'Hello, my name is Olivia. I am from Germany and I have a big family.',
      'Hi, my name is Olivia. I am from Turkey and I have a sister.',
      'Hello, my family is from Germany. My name is Olivia.',
      'Hi, I am Olivia. My brother is from Germany.',
    ],
    x: 200,
    y: 2550,
    unit: 3,
    extra: true,
  },
  {
    id: 'q3e2',
    type: 'matching',
    description: 'Türkçe kelimeleri İngilizce karşılıklarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Aile', 'Kız kardeş', 'Japonya', 'Çay'],
    rightOptions: ['Family', 'Sister', 'Japan', 'Tea'],
    correctPairs: [
      { left: 'Aile', right: 'Family' },
      { left: 'Kız kardeş', right: 'Sister' },
      { left: 'Japonya', right: 'Japan' },
      { left: 'Çay', right: 'Tea' },
    ],
    x: 100,
    y: 2650,
    unit: 3,
    extra: true,
  },  
  {
    id: 'q3e3',
    type: 'listening',
    description: 'Dinleyin ve uzun cümleyi oluşturun',
    sentence: 'My name is Daniel and I live in Canada with my parents and two sisters.',
    correctAnswer: 'My name is Daniel and I live in Canada with my parents and two sisters.',
    options: [],
    words: ['My', 'name', 'is', 'Daniel', 'and', 'I', 'live', 'in', 'Canada', 'with', 'my', 'parents', 'and', 'two', 'sisters'],
    x: 200,
    y: 2750,
    unit: 3,
    extra: true,
  },
  {
    id: 'q3e4',
    type: 'speaking',
    description: 'Bu uzun cümleyi sesli söyleyin',
    sentence: 'This is my brother Alex. He is from Italy and he speaks Italian and English.',
    correctAnswer: 'This is my brother Alex. He is from Italy and he speaks Italian and English.',
    options: [],
    x: 100,
    y: 2850,
    unit: 3,
    extra: true,
  },
  {
    id: 'q3e5',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "aile"',
    sentence: 'Family',
    correctAnswer: 'aile',
    options: [],
    x: 200,
    y: 2950,
    unit: 3,
    extra: true,
    images: [
      { label: 'aile', image: require('./assets/images/family.png') },         // ✅ doğru
      { label: 'erkek kardeş', image: require('./assets/images/brother.png') },
      { label: 'anne', image: require('./assets/images/mom.png') },
      { label: 'baba', image: require('./assets/images/dad.png') },
    ],
  },  
  //ünite 4 soruları
  {
    id: 'q76',
    type: 'translation',
    description: '"Bu benim çantam."',
    sentence: 'Bu benim çantam.',
    correctAnswer: 'This is my bag.',
    options: ['This is my bag.', 'This is your passport.', 'This is a ticket.', 'This is my phone.'],
    x: 100,
    y: 50,
    unit: 4,
  },
  {
    id: 'q77',
    type: 'translation',
    description: '"Senin biletin lütfen."',
    sentence: 'Senin biletin lütfen.',
    correctAnswer: 'Your ticket, please.',
    options: ['Your ticket, please.', 'My passport, please.', 'This is your gate.', 'Where is your bag?'],
    x: 200,
    y: 150,
    unit: 4,
  },
  {
    id: 'q78',
    type: 'translation',
    description: '"Evet, bu benim telefonum."',
    sentence: 'Evet, bu benim telefonum.',
    correctAnswer: 'Yes, this is my phone.',
    options: ['Yes, this is my phone.', 'No, this is my passport.', 'Yes, this is a ticket.', 'This is your phone.'],
    x: 100,
    y: 250,
    unit: 4,
  },
  {
    id: 'q79',
    type: 'translation',
    description: '"Hoş geldiniz!"',
    sentence: 'Hoş geldiniz!',
    correctAnswer: 'Welcome!',
    options: ['Welcome!', 'Goodbye!', 'Hello!', 'Please!'],
    x: 200,
    y: 350,
    unit: 4,
  },
  {
    id: 'q80',
    type: 'translation',
    description: '"Bu senin kapın mı?"',
    sentence: 'Bu senin kapın mı?',
    correctAnswer: 'Is this your gate?',
    options: ['Is this your gate?', 'Is this your phone?', 'This is my gate.', 'Where is your gate?'],
    x: 100,
    y: 450,
    unit: 4,
  },
  {
    id: 'q81',
    type: 'matching',
    description: 'Kelimeleri eşleştirin.',
    sentence: '',
    correctAnswer: '',
    options: [],
    x: 200,
    y: 550,
    unit: 4,
    leftOptions: ['Bilet', 'Pasaport', 'Çanta', 'Telefon'],
    rightOptions: ['Ticket', 'Passport', 'Bag', 'Phone'],
    correctPairs: [
      { left: 'Bilet', right: 'Ticket' },
      { left: 'Pasaport', right: 'Passport' },
      { left: 'Çanta', right: 'Bag' },
      { left: 'Telefon', right: 'Phone' },
    ],
  },
  {
    id: 'q82',
    type: 'matching',
    description: 'Kelimeleri eşleştirin.',
    sentence: '',
    correctAnswer: '',
    options: [],
    x: 100,
    y: 650,
    unit: 4,
    leftOptions: ['Kapı', 'Hoş geldiniz', 'Süt', 'Japonya'],
    rightOptions: ['Gate', 'Welcome', 'Milk', 'Japan'],
    correctPairs: [
      { left: 'Kapı', right: 'Gate' },
      { left: 'Hoş geldiniz', right: 'Welcome' },
      { left: 'Süt', right: 'Milk' },
      { left: 'Japonya', right: 'Japan' },
    ],
  },
  {
    id: 'q83',
    type: 'matching',
    description: 'Kelimeleri eşleştirin.',
    sentence: '',
    correctAnswer: '',
    options: [],
    x: 200,
    y: 750,
    unit: 4,
    leftOptions: ['Ceket', 'Süt', 'Japonya', 'Çanta'],
    rightOptions: ['Jacket', 'Milk', 'Japan', 'Bag'],
    correctPairs: [
      { left: 'Ceket', right: 'Jacket' },
      { left: 'Süt', right: 'Milk' },
      { left: 'Japonya', right: 'Japan' },
      { left: 'Çanta', right: 'Bag' },
    ],
  },  
  {
    id: 'q84',
    type: 'matching',
    description: 'Kelimeleri eşleştirin.',
    sentence: '',
    correctAnswer: '',
    options: [],
    x: 100,
    y: 850,
    unit: 4,
    leftOptions: ['Kitap', 'Kız kardeş', 'Gümrük', 'Fransa'],
    rightOptions: ['Book', 'Sister', 'Customs', 'France'],
    correctPairs: [
      { left: 'Kitap', right: 'Book' },
      { left: 'Kız kardeş', right: 'Sister' },
      { left: 'Gümrük', right: 'Customs' },
      { left: 'Fransa', right: 'France' },
    ],
  },
  {
    id: 'q85',
    type: 'matching',
    description: 'Kelimeleri eşleştirin.',
    sentence: '',
    correctAnswer: '',
    options: [],
    x: 200,
    y: 950,
    unit: 4,
    leftOptions: ['Çay', 'Mont', 'Annem', 'Selam'],
    rightOptions: ['Tea', 'Jacket', 'My mom', 'Hi'],
    correctPairs: [
      { left: 'Çay', right: 'Tea' },
      { left: 'Mont', right: 'Jacket' },
      { left: 'Annem', right: 'My mom' },
      { left: 'Selam', right: 'Hi' },
    ],
  },
  {
    id: 'q86',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'This is my passport.',
    correctAnswer: 'This is my passport.',
    options: [],
    words: ['This', 'is', 'my', 'passport', 'ticket', 'bag'],
    x: 100,
    y: 1050,
    unit: 4,
  },
  {
    id: 'q87',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'Your phone, please.',
    correctAnswer: 'Your phone, please.',
    options: [],
    words: ['Your', 'phone', 'please', 'ticket', 'my'],
    x: 200,
    y: 1150,
    unit: 4,
  },
  {
    id: 'q88',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'Is this your bag?',
    correctAnswer: 'Is this your bag?',
    options: [],
    words: ['Is', 'this', 'your', 'bag', 'jacket', 'passport'],
    x: 100,
    y: 1250,
    unit: 4,
  },
  {
    id: 'q89',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'Welcome to Paris.',
    correctAnswer: 'Welcome to Paris.',
    options: [],
    words: ['Welcome', 'to', 'Paris', 'Japan', 'Hello'],
    x: 200,
    y: 1350,
    unit: 4,
  },
  {
    id: 'q90',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'This is my jacket.',
    correctAnswer: 'This is my jacket.',
    options: [],
    words: ['This', 'is', 'my', 'jacket', 'bag', 'milk'],
    x: 100,
    y: 1450,
    unit: 4,
  },
  {
    id: 'q91',
    type: 'speaking',
    description: 'Bu cümleyi sesli okuyun: "This is my bag."',
    sentence: 'This is my bag.',
    correctAnswer: 'This is my bag.',
    options: [],
    x: 200,
    y: 1550,
    unit: 4,
  },
  {
    id: 'q92',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "Your passport, please."',
    sentence: 'Your passport, please.',
    correctAnswer: 'Your passport, please.',
    options: [],
    x: 100,
    y: 1650,
    unit: 4,
  },
  {
    id: 'q93',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "Welcome to Japan!"',
    sentence: 'Welcome to Japan!',
    correctAnswer: 'Welcome to Japan!',
    options: [],
    x: 200,
    y: 1750,
    unit: 4,
  },
  {
    id: 'q94',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "Is this your ticket?"',
    sentence: 'Is this your ticket?',
    correctAnswer: 'Is this your ticket?',
    options: [],
    x: 100,
    y: 1850,
    unit: 4,
  },
  {
    id: 'q95',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "This is customs."',
    sentence: 'This is customs.',
    correctAnswer: 'This is customs.',
    options: [],
    x: 200,
    y: 1950,
    unit: 4,
  },
  {
    id: 'q96',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "bilet"',
    sentence: 'Ticket',
    correctAnswer: 'bilet',
    options: [],
    x: 100,
    y: 2050,
    unit: 4,
    images: [
      { label: 'bilet', image: require('./assets/images/ticket.png') },
      { label: 'pasaport', image: require('./assets/images/passport.png') },
      { label: 'çanta', image: require('./assets/images/bag.png') },
      { label: 'telefon', image: require('./assets/images/phone.png') },
    ],
  },
  {
    id: 'q97',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "pasaport"',
    sentence: 'Passport',
    correctAnswer: 'pasaport',
    options: [],
    x: 200,
    y: 2150,
    unit: 4,
    images: [
      { label: 'pasaport', image: require('./assets/images/passport.png') },
      { label: 'bilet', image: require('./assets/images/ticket.png') },
      { label: 'çanta', image: require('./assets/images/bag.png') },
      { label: 'telefon', image: require('./assets/images/phone.png') },
    ],
  },
  {
    id: 'q98',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "çanta"',
    sentence: 'Bag',
    correctAnswer: 'çanta',
    options: [],
    x: 100,
    y: 2250,
    unit: 4,
    images: [
      { label: 'çanta', image: require('./assets/images/bag.png') },
      { label: 'mont', image: require('./assets/images/jacket.png') },
      { label: 'şeker', image: require('./assets/images/sugar.png') },
      { label: 'süt', image: require('./assets/images/milk.png') },
    ],
  },
  {
    id: 'q99',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "telefon"',
    sentence: 'Phone',
    correctAnswer: 'telefon',
    options: [],
    x: 200,
    y: 2350,
    unit: 4,
    images: [
      { label: 'telefon', image: require('./assets/images/phone.png') },
      { label: 'çanta', image: require('./assets/images/bag.png') },
      { label: 'mont', image: require('./assets/images/jacket.png') },
      { label: 'kapı', image: require('./assets/images/gate.png') },
    ],
  },
  {
    id: 'q100',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "gümrük"',
    sentence: 'Customs',
    correctAnswer: 'gümrük',
    options: [],
    x: 100,
    y: 2450,
    unit: 4,
    images: [
      { label: 'gümrük', image: require('./assets/images/customs.png') },
      { label: 'kapı', image: require('./assets/images/gate.png') },
      { label: 'telefon', image: require('./assets/images/phone.png') },
      { label: 'pasaport', image: require('./assets/images/passport.png') },
    ],
  },
  {
    id: 'q4e1',
    type: 'translation',
    description: 'Cümleyi doğru çevir: "Lütfen biletinizi ve pasaportunuzu gösterin."',
    sentence: 'Lütfen biletinizi ve pasaportunuzu gösterin.',
    correctAnswer: 'Please show your ticket and passport.',
    options: [
      'Please show your ticket and passport.',
      'Please give me your passport and phone.',
      'Your gate is here.',
      'This is your bag and phone.'
    ],
    x: 200,
    y: 2550,
    unit: 4,
    extra: true
  },
  {
    id: 'q4e2',
    type: 'matching',
    description: 'Türkçe kelimeleri İngilizce karşılıklarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Mont', 'Gümrük', 'Kapı', 'Bilet'],
    rightOptions: ['Jacket', 'Customs', 'Gate', 'Ticket'],
    correctPairs: [
      { left: 'Mont', right: 'Jacket' },
      { left: 'Gümrük', right: 'Customs' },
      { left: 'Kapı', right: 'Gate' },
      { left: 'Bilet', right: 'Ticket' }
    ],
    x: 100,
    y: 2650,
    unit: 4,
    extra: true
  },
  {
    id: 'q4e3',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: 'I need to find the customs and gate B12.',
    correctAnswer: 'I need to find the customs and gate B12.',
    options: [],
    words: ['I', 'need', 'to', 'find', 'the', 'customs', 'and', 'gate', 'B12'],
    x: 200,
    y: 2750,
    unit: 4,
    extra: true
  },
  {
    id: 'q4e4',
    type: 'speaking',
    description: 'Bu cümleyi yüksek sesle okuyun',
    sentence: 'This is your gate. Please go straight and turn left.',
    correctAnswer: 'This is your gate. Please go straight and turn left.',
    options: [],
    x: 100,
    y: 2850,
    unit: 4,
    extra: true
  },
  {
    id: 'q4e5',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "giriş kapısı"',
    sentence: 'Gate',
    correctAnswer: 'giriş kapısı',
    options: [],
    x: 200,
    y: 2950,
    unit: 4,
    extra: true,
    images: [
      { label: 'giriş kapısı', image: require('./assets/images/gate.png') },     // ✅ doğru
      { label: 'mont', image: require('./assets/images/jacket.png') },
      { label: 'pasaport', image: require('./assets/images/passport.png') },
      { label: 'telefon', image: require('./assets/images/phone.png') },
    ]
  },

  {
    id: 'q101',
    type: 'translation',
    description: '"Bu şehir güzel."',
    sentence: 'Bu şehir güzel.',
    correctAnswer: 'This city is nice.',
    options: ['This city is nice.', 'This house is nice.', 'This park is nice.', 'My city is quiet.'],
    x: 100,
    y: 50,
    unit: 5,
  },
  {
    id: 'q102',
    type: 'translation',
    description: '"O restoran çok işlek."',
    sentence: 'O restoran çok işlek.',
    correctAnswer: 'That restaurant is very busy.',
    options: ['This library is very quiet.', 'That restaurant is very busy.', 'This museum is very nice.', 'The park is small.'],
    x: 200,
    y: 150,
    unit: 5,
  },
  {
    id: 'q103',
    type: 'translation',
    description: '"Bu sokak sakin."',
    sentence: 'Bu sokak sakin.',
    correctAnswer: 'This street is quiet.',
    options: ['This park is busy.', 'This street is quiet.', 'This street is busy.', 'The street is very old.'],
    x: 100,
    y: 250,
    unit: 5,
  },
  {
    id: 'q104',
    type: 'translation',
    description: '"Kütüphane çok eski."',
    sentence: 'Kütüphane çok eski.',
    correctAnswer: 'The library is very old.',
    options: ['The museum is very old.', 'The restaurant is new.', 'The library is very old.', 'The park is beautiful.'],
    x: 200,
    y: 350,
    unit: 5,
  },
  {
    id: 'q105',
    type: 'translation',
    description: '"Şehir büyük, değil mi?"',
    sentence: 'Şehir büyük, değil mi?',
    correctAnswer: 'The city is big, right?',
    options: ['The city is small.', 'The city is big, right?', 'The city is nice.', 'The house is big.'],
    x: 100,
    y: 450,
    unit: 5,
  },
  {
    id: 'q106',
    type: 'matching',
    description: 'İngilizce kelimeleri Türkçeleriyle eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Kütüphane', 'Şehir', 'Müze', 'Cadde'],
    rightOptions: ['Library', 'City', 'Museum', 'Street'],
    correctPairs: [
      { left: 'Kütüphane', right: 'Library' },
      { left: 'Şehir', right: 'City' },
      { left: 'Müze', right: 'Museum' },
      { left: 'Cadde', right: 'Street' }
    ],
    x: 200,
    y: 550,
    unit: 5,
  },
  {
    id: 'q107',
    type: 'matching',
    description: 'İngilizce sıfatları anlamlarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['İşlek', 'Eski', 'Büyük', 'Güzel'],
    rightOptions: ['Busy', 'Old', 'Big', 'Nice'],
    correctPairs: [
      { left: 'İşlek', right: 'Busy' },
      { left: 'Eski', right: 'Old' },
      { left: 'Büyük', right: 'Big' },
      { left: 'Güzel', right: 'Nice' }
    ],
    x: 100,
    y: 650,
    unit: 5,
  },
  {
    id: 'q108',
    type: 'matching',
    description: 'Kurumları ve İngilizce karşılıklarını eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Kütüphane', 'Restoran', 'Üniversite', 'Park'],
    rightOptions: ['Library', 'Restaurant', 'University', 'Park'],
    correctPairs: [
      { left: 'Kütüphane', right: 'Library' },
      { left: 'Restoran', right: 'Restaurant' },
      { left: 'Üniversite', right: 'University' },
      { left: 'Park', right: 'Park' },
    ],
    x: 200,
    y: 750,
    unit: 5,
  },
  {
    id: 'q109',
    type: 'matching',
    description: 'Kelimeleri eşleştirin.',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Selam', 'Ceket', 'Güzel', 'Cadde'],
    rightOptions: ['Hi', 'Jacket', 'Nice', 'Street'],
    correctPairs: [
      { left: 'Selam', right: 'Hi' },
      { left: 'Ceket', right: 'Jacket' },
      { left: 'Güzel', right: 'Nice' },
      { left: 'Cadde', right: 'Street' },
    ],
    x: 100,
    y: 850,
    unit: 5,
  },
  {
    id: 'q110',
    type: 'matching',
    description: 'Kelimeleri eşleştirin.',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Müze', 'Üniversite', 'Ünlü', 'Güzel'],
    rightOptions: ['Museum', 'University', 'Famous', 'Nice'],
    correctPairs: [
      { left: 'Müze', right: 'Museum' },
      { left: 'Üniversite', right: 'University' },
      { left: 'Ünlü', right: 'Famous' },
      { left: 'Güzel', right: 'Nice' },
    ],
    x: 200,
    y: 950,
    unit: 5,
  },
  {
    id: 'q111',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'This city is big.',
    correctAnswer: 'This city is big.',
    options: [],
    words: ['This', 'city', 'is', 'big', 'park', 'library'],
    x: 100,
    y: 1050,
    unit: 5,
  },
  {
    id: 'q112',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'The restaurant is very busy.',
    correctAnswer: 'The restaurant is very busy.',
    options: [],
    words: ['The', 'restaurant', 'is', 'very', 'busy', 'quiet'],
    x: 200,
    y: 1150,
    unit: 5,
  },
  {
    id: 'q113',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'This museum is old.',
    correctAnswer: 'This museum is old.',
    options: [],
    words: ['This', 'museum', 'is', 'old', 'big', 'very'],
    x: 100,
    y: 1250,
    unit: 5,
  },
  {
    id: 'q114',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'My house is very nice.',
    correctAnswer: 'My house is very nice.',
    options: [],
    words: ['My', 'house', 'is', 'very', 'nice', 'park'],
    x: 200,
    y: 1350,
    unit: 5,
  },
  {
    id: 'q115',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'Welcome to the quiet street.',
    correctAnswer: 'Welcome to the quiet street.',
    options: [],
    words: ['Welcome', 'to', 'the', 'quiet', 'street', 'museum'],
    x: 100,
    y: 1450,
    unit: 5,
  },
  {
    id: 'q116',
    type: 'speaking',
    description: 'Bu cümleyi okuyun',
    sentence: 'This city is very big.',
    correctAnswer: 'This city is very big.',
    options: [],
    x: 200,
    y: 1550,
    unit: 5,
  },
  {
    id: 'q117',
    type: 'speaking',
    description: 'Bu cümleyi okuyun',
    sentence: 'My house is quiet and old.',
    correctAnswer: 'My house is quiet and old.',
    options: [],
    x: 100,
    y: 1650,
    unit: 5,
  },
  {
    id: 'q118',
    type: 'speaking',
    description: 'Bu cümleyi okuyun',
    sentence: 'This park is very nice.',
    correctAnswer: 'This park is very nice.',
    options: [],
    x: 200,
    y: 1750,
    unit: 5,
  },
  {
    id: 'q119',
    type: 'speaking',
    description: 'Bu cümleyi okuyun',
    sentence: 'The university is very famous.',
    correctAnswer: 'The university is very famous.',
    options: [],
    x: 100,
    y: 1850,
    unit: 5,
  },
  {
    id: 'q120',
    type: 'speaking',
    description: 'Bu cümleyi okuyun',
    sentence: 'Where is the library?',
    correctAnswer: 'Where is the library?',
    options: [],
    x: 200,
    y: 1950,
    unit: 5,
  },
  {
    id: 'q121',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "cadde"',
    sentence: 'Street',
    correctAnswer: 'cadde',
    options: [],
    x: 100,
    y: 2050,
    unit: 5,
    images: [
      { label: 'cadde', image: require('./assets/images/street.png') },
      { label: 'pasaport', image: require('./assets/images/passport.png') },
      { label: 'telefon', image: require('./assets/images/phone.png') },
      { label: 'restoran', image: require('./assets/images/restaurant.png') },
    ],
  },
  {
    id: 'q122',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "müze"',
    sentence: 'Museum',
    correctAnswer: 'müze',
    options: [],
    x: 200,
    y: 2150,
    unit: 5,
    images: [
      { label: 'müze', image: require('./assets/images/museum.png') },
      { label: 'ev', image: require('./assets/images/house.png') },
      { label: 'üniversite', image: require('./assets/images/university.png') },
      { label: 'şehir', image: require('./assets/images/city.png') },
    ],
  },
  {
    id: 'q123',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "park"',
    sentence: 'Park',
    correctAnswer: 'park',
    options: [],
    x: 100,
    y: 2250,
    unit: 5,
    images: [
      { label: 'park', image: require('./assets/images/park.png') },
      { label: 'cadde', image: require('./assets/images/street.png') },
      { label: 'kütüphane', image: require('./assets/images/library.png') },
      { label: 'restoran', image: require('./assets/images/restaurant.png') },
    ],
  },
  {
    id: 'q124',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "üniversite"',
    sentence: 'University',
    correctAnswer: 'üniversite',
    options: [],
    x: 200,
    y: 2350,
    unit: 5,
    images: [
      { label: 'üniversite', image: require('./assets/images/university.png') },
      { label: 'ev', image: require('./assets/images/house.png') },
      { label: 'şehir', image: require('./assets/images/city.png') },
      { label: 'telefon', image: require('./assets/images/phone.png') },
    ],
  },
  {
    id: 'q125',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "kütüphane"',
    sentence: 'Library',
    correctAnswer: 'kütüphane',
    options: [],
    x: 100,
    y: 2450,
    unit: 5,
    images: [
      { label: 'kütüphane', image: require('./assets/images/library.png') },
      { label: 'park', image: require('./assets/images/park.png') },
      { label: 'şehir', image: require('./assets/images/city.png') },
      { label: 'restoran', image: require('./assets/images/restaurant.png') },
    ],
  },
  {
    id: 'q5e1',
    type: 'translation',
    description: 'Cümleyi çevirin: "Bu sokak çok sakin ama park çok işlek."',
    sentence: 'Bu sokak çok sakin ama park çok işlek.',
    correctAnswer: 'This street is very quiet but the park is very busy.',
    options: [
      'This street is very quiet but the park is very busy.',
      'This city is small and quiet.',
      'The park is nice but the street is busy.',
      'This street and park are big.'
    ],
    x: 200,
    y: 2550,
    unit: 5,
    extra: true,
  },
  {
    id: 'q5e2',
    type: 'matching',
    description: 'Sıfatları ve isimleri anlamlı şekilde eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Sessiz kütüphane', 'Büyük şehir', 'Ünlü müze', 'Eski ev'],
    rightOptions: ['Quiet library', 'Big city', 'Famous museum', 'Old house'],
    correctPairs: [
      { left: 'Sessiz kütüphane', right: 'Quiet library' },
      { left: 'Büyük şehir', right: 'Big city' },
      { left: 'Ünlü müze', right: 'Famous museum' },
      { left: 'Eski ev', right: 'Old house' }
    ],
    x: 100,
    y: 2650,
    unit: 5,
    extra: true
  },
  {
    id: 'q5e3',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun: "The museum is small but very famous."',
    sentence: 'The museum is small but very famous.',
    correctAnswer: 'The museum is small but very famous.',
    options: [],
    words: ['The', 'museum', 'is', 'small', 'but', 'very', 'famous'],
    x: 200,
    y: 2750,
    unit: 5,
    extra: true,
  },
  {
    id: 'q5e4',
    type: 'speaking',
    description: 'Bu cümleyi okuyun',
    sentence: 'That street is very busy, especially in the morning.',
    correctAnswer: 'That street is very busy, especially in the morning.',
    options: [],
    x: 100,
    y: 2850,
    unit: 5,
    extra: true,
  },
  {
    id: 'q5e5',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "ünlü üniversite"',
    sentence: 'Famous university',
    correctAnswer: 'ünlü üniversite',
    options: [],
    x: 200,
    y: 2950,
    unit: 5,
    extra: true,
    images: [
      { label: 'ünlü üniversite', image: require('./assets/images/famous_university.png') }, // doğru
      { label: 'şehir', image: require('./assets/images/city.png') },
      { label: 'restoran', image: require('./assets/images/restaurant.png') },
      { label: 'kütüphane', image: require('./assets/images/library.png') },
    ]
  },
  
  {
    id: 'q126',
    type: 'translation',
    description: '"Merhaba, bir menü istiyorum."',
    sentence: 'Merhaba, bir menü istiyorum.',
    correctAnswer: "Hi, I'd like a menu.",
    options: [
      "Hi, I'd like a menu.",
      "Goodbye, here is your menu.",
      "Hello, you want menu.",
      "Yes, this is a menu."
    ],
    x: 100,
    y: 50,
    unit: 6,
  },
  {
    id: 'q127',
    type: 'translation',
    description: '"Bu pizza çok pahalı."',
    sentence: 'Bu pizza çok pahalı.',
    correctAnswer: 'This pizza is very expensive.',
    options: [
      'This pizza is very expensive.',
      'That pizza is cheap.',
      'My pizza is delicious.',
      'This is a small salad.'
    ],
    x: 200,
    y: 150,
    unit: 6,
  },
  {
    id: 'q128',
    type: 'translation',
    description: '"Lütfen bir sandviç ve bir bardak su istiyorum."',
    sentence: 'Lütfen bir sandviç ve bir bardak su istiyorum.',
    correctAnswer: "I'd like a sandwich and a glass of water, please.",
    options: [
      "I'd like a sandwich and a glass of water, please.",
      "Where is my water and sandwich?",
      "This sandwich and tea are delicious.",
      "I want soup and dessert."
    ],
    x: 100,
    y: 250,
    unit: 6,
  },
  {
    id: 'q129',
    type: 'translation',
    description: '"Affedersiniz, bu benim pizzam mı?"',
    sentence: 'Affedersiniz, bu benim pizzam mı?',
    correctAnswer: 'Excuse me, is this my pizza?',
    options: [
      'Excuse me, is this my pizza?',
      'Where is my soup?',
      'Hi, I want pizza please.',
      'No, this is not pizza.'
    ],
    x: 200,
    y: 350,
    unit: 6,
  },
  {
    id: 'q130',
    type: 'translation',
    description: 'Cümleye göre doğru kelimeyi seçin: This small burger is delicious! Here is your salad and your pizza, Lisa.\n\nThis burger is ...',
    sentence: 'This small burger is delicious! Here is your salad and your pizza, Lisa.\n\nThis burger is ...',
    correctAnswer: 'small',
    options: ['small', 'large', 'quiet', 'old'],
    x: 100,
    y: 450,
    unit: 6
  },  
  {
    id: 'q131',
    type: 'matching',
    description: 'Türkçe kelimeleri İngilizce karşılıklarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Çorba', 'Menü', 'Pizza', 'Salata'],
    rightOptions: ['Soup', 'Menu', 'Pizza', 'Salad'],
    correctPairs: [
      { left: 'Çorba', right: 'Soup' },
      { left: 'Menü', right: 'Menu' },
      { left: 'Pizza', right: 'Pizza' },
      { left: 'Salata', right: 'Salad' }
    ],
    x: 200,
    y: 550,
    unit: 6,
  },
  {
    id: 'q132',
    type: 'matching',
    description: 'Türkçe kelimeleri İngilizce karşılıklarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Tatlı', 'Restoran', 'Sandviç', 'Bardak'],
    rightOptions: ['Dessert', 'Restaurant', 'Sandwich', 'Glass'],
    correctPairs: [
      { left: 'Tatlı', right: 'Dessert' },
      { left: 'Restoran', right: 'Restaurant' },
      { left: 'Sandviç', right: 'Sandwich' },
      { left: 'Bardak', right: 'Glass' }
    ],
    x: 100,
    y: 650,
    unit: 6,
  },
  {
    id: 'q133',
    type: 'matching',
    description: 'Türkçe kelimeleri İngilizce karşılıklarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Kase', 'Su', 'Büyük', 'Lezzetli'],
    rightOptions: ['Bowl', 'Water', 'Large', 'Delicious'],
    correctPairs: [
      { left: 'Kase', right: 'Bowl' },
      { left: 'Su', right: 'Water' },
      { left: 'Büyük', right: 'Large' },
      { left: 'Lezzetli', right: 'Delicious' }
    ],
    x: 200,
    y: 750,
    unit: 6,
  },
  {
    id: 'q134',
    type: 'matching',
    description: 'Türkçe kelimeleri İngilizce karşılıklarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Lütfen', 'Affedersiniz', 'Benim', 'Nerede'],
    rightOptions: ['Please', 'Excuse me', 'My', 'Where'],
    correctPairs: [
      { left: 'Lütfen', right: 'Please' },
      { left: 'Affedersiniz', right: 'Excuse me' },
      { left: 'Benim', right: 'My' },
      { left: 'Nerede', right: 'Where' }
    ],
    x: 100,
    y: 850,
    unit: 6,
  },
  {
    id: 'q135',
    type: 'matching',
    description: 'Türkçe kelimeleri İngilizce karşılıklarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Çay', 'Burger', 'Küçük', 'Burada'],
    rightOptions: ['Tea', 'Burger', 'Small', 'Here'],
    correctPairs: [
      { left: 'Çay', right: 'Tea' },
      { left: 'Burger', right: 'Burger' },
      { left: 'Küçük', right: 'Small' },
      { left: 'Burada', right: 'Here' }
    ],
    x: 200,
    y: 950,
    unit: 6,
  },
  {
    id: 'q136',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: "I'd like a pizza please",
    correctAnswer: "I'd like a pizza please",
    options: [],
    words: ["I'd", "like", "a", "pizza", "please", "salad"],
    x: 100,
    y: 1050,
    unit: 6,
  },  
  {
    id: 'q137',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: "This soup is delicious",
    correctAnswer: "This soup is delicious",
    options: [],
    words: ["This", "soup", "is", "delicious", "my", "tea"],
    x: 200,
    y: 1150,
    unit: 6,
  },
  {
    id: 'q138',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: "Excuse me, where is my salad?",
    correctAnswer: "Excuse me, where is my salad?",
    options: [],
    words: ["Excuse", "me,", "where", "is", "my", "salad?"],
    x: 100,
    y: 1250,
    unit: 6,
  },
  {
    id: 'q139',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: "Here is your tea and dessert",
    correctAnswer: "Here is your tea and dessert",
    options: [],
    words: ["Here", "is", "your", "tea", "and", "dessert"],
    x: 200,
    y: 1350,
    unit: 6,
  },
  {
    id: 'q140',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: "I'd like a menu and a glass of water",
    correctAnswer: "I'd like a menu and a glass of water",
    options: [],
    words: ["I'd", "like", "a", "menu", "and", "a", "glass", "of", "water"],
    x: 100,
    y: 1450,
    unit: 6,
  },
  {
    id: 'q141',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "Hi, I’d like a menu, please."',
    sentence: "Hi, I’d like a menu, please.",
    correctAnswer: "Hi, I’d like a menu, please.",
    options: [],
    x: 200,
    y: 1550,
    unit: 6,
  },
  {
    id: 'q142',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "This salad is delicious."',
    sentence: "This salad is delicious.",
    correctAnswer: "This salad is delicious.",
    options: [],
    x: 100,
    y: 1650,
    unit: 6,
  },
  {
    id: 'q143',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "Where is my burger?"',
    sentence: "Where is my burger?",
    correctAnswer: "Where is my burger?",
    options: [],
    x: 200,
    y: 1750,
    unit: 6,
  },
  {
    id: 'q144',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "Excuse me, is this my tea?"',
    sentence: "Excuse me, is this my tea?",
    correctAnswer: "Excuse me, is this my tea?",
    options: [],
    x: 100,
    y: 1850,
    unit: 6,
  },
  {
    id: 'q145',
    type: 'speaking',
    description: 'Bu cümleyi okuyun: "I’d like a bowl of soup and a small pizza."',
    sentence: "I’d like a bowl of soup and a small pizza.",
    correctAnswer: "I’d like a bowl of soup and a small pizza.",
    options: [],
    x: 200,
    y: 1950,
    unit: 6,
  },
  {
    id: 'q146',
    type: 'imageChoice',
    description: 'Doğru görseli seçin',
    sentence: 'Sandwich',
    correctAnswer: 'sandviç',
    options: [],
    x: 100,
    y: 2050,
    unit: 6,
    images: [
      { label: 'sandviç', image: require('./assets/images/sandwich.png') },
      { label: 'salata', image: require('./assets/images/salad.png') },
      { label: 'çorba', image: require('./assets/images/soup.png') },
      { label: 'su', image: require('./assets/images/water.png') },
    ],
  },
  {
    id: 'q147',
    type: 'imageChoice',
    description: 'Doğru görseli seçin',
    sentence: 'Menu',
    correctAnswer: 'menü',
    options: [],
    x: 200,
    y: 2150,
    unit: 6,
    images: [
      { label: 'menü', image: require('./assets/images/menu.png') },
      { label: 'çay', image: require('./assets/images/tea.png') },
      { label: 'tatlı', image: require('./assets/images/dessert.png') },
      { label: 'burger', image: require('./assets/images/burger.png') },
    ],
  },
  {
    id: 'q148',
    type: 'imageChoice',
    description: 'Doğru görseli seçin',
    sentence: 'A glass of water',
    correctAnswer: 'su',
    options: [],
    x: 100,
    y: 2250,
    unit: 6,
    images: [
      { label: 'su', image: require('./assets/images/water.png') },
      { label: 'süt', image: require('./assets/images/milk.png') },
      { label: 'çay', image: require('./assets/images/tea.png') },
      { label: 'meyve suyu', image: require('./assets/images/juice.png') },
    ],
  },
  {
    id: 'q149',
    type: 'imageChoice',
    description: 'Doğru görseli seçin',
    sentence: 'A bowl of soup',
    correctAnswer: 'çorba',
    options: [],
    x: 200,
    y: 2350,
    unit: 6,
    images: [
      { label: 'çorba', image: require('./assets/images/soup.png') },
      { label: 'pizza', image: require('./assets/images/pizza.png') },
      { label: 'burger', image: require('./assets/images/burger.png') },
      { label: 'salata', image: require('./assets/images/salad.png') },
    ],
  },
  {
    id: 'q150',
    type: 'imageChoice',
    description: 'Doğru görseli seçin',
    sentence: 'Dessert',
    correctAnswer: 'tatlı',
    options: [],
    x: 100,
    y: 2450,
    unit: 6,
    images: [
      { label: 'tatlı', image: require('./assets/images/dessert.png') },
      { label: 'çay', image: require('./assets/images/tea.png') },
      { label: 'çorba', image: require('./assets/images/soup.png') },
      { label: 'sandviç', image: require('./assets/images/sandwich.png') },
    ],
  },
  {
    id: 'q6e1',
    type: 'translation',
    description: '"Lütfen bir kase çorba, küçük bir pizza ve tatlı istiyorum."',
    sentence: 'Lütfen bir kase çorba, küçük bir pizza ve tatlı istiyorum.',
    correctAnswer: "I'd like a bowl of soup, a small pizza and a dessert, please.",
    options: [
      "I'd like a bowl of soup, a small pizza and a dessert, please.",
      "This is a soup and salad.",
      "My tea and sandwich, please.",
      "I'd like a big pizza and water."
    ],
    x: 200,
    y: 2550,
    unit: 6,
    extra: true
  },
  {
    id: 'q6e2',
    type: 'matching',
    description: 'Kelimeleri eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Su', 'Küçük', 'Sandviç', 'Burada'],
    rightOptions: ['Water', 'Small', 'Sandwich', 'Here'],
    correctPairs: [
      { left: 'Su', right: 'Water' },
      { left: 'Küçük', right: 'Small' },
      { left: 'Sandviç', right: 'Sandwich' },
      { left: 'Burada', right: 'Here' }
    ],
    x: 100,
    y: 2650,
    unit: 6,
    extra: true
  },
  {
    id: 'q6e3',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: "Excuse me, where is my glass of water?",
    correctAnswer: "Excuse me, where is my glass of water?",
    options: [],
    words: ['Excuse', 'me,', 'where', 'is', 'my', 'glass', 'of', 'water?'],
    x: 200,
    y: 2750,
    unit: 6,
    extra: true
  },
  {
    id: 'q6e4',
    type: 'speaking',
    description: 'Bu cümleyi okuyun',
    sentence: "This pizza is too expensive, I want something cheap.",
    correctAnswer: "This pizza is too expensive, I want something cheap.",
    options: [],
    x: 100,
    y: 2850,
    unit: 6,
    extra: true
  },
  {
    id: 'q6e5',
    type: 'imageChoice',
    description: 'Doğru görseli seçin: "küçük bir pizza"',
    sentence: 'A small pizza',
    correctAnswer: 'küçük pizza',
    options: [],
    x: 200,
    y: 2950,
    unit: 6,
    extra: true,
    images: [
      { label: 'küçük pizza', image: require('./assets/images/pizza.png') },
      { label: 'burger', image: require('./assets/images/burger.png') },
      { label: 'tatlı', image: require('./assets/images/dessert.png') },
      { label: 'su', image: require('./assets/images/water.png') },
    ],
  },  
  
  {
    id: 'q151',
    type: 'translation',
    description: 'Ben de doktorum.',
    sentence: 'Ben de doktorum.',
    correctAnswer: "I'm a doctor too.",
    options: [
      "I'm a teacher too.",
      "I'm a doctor too.",
      "She's a doctor too.",
      "I'm a student.",
    ],
    x: 100, y: 50, unit: 7,
  },
  {
    id: 'q152',
    type: 'translation',
    description: 'Eşin öğretmen, değil mi?',
    sentence: 'Eşin öğretmen, değil mi?',
    correctAnswer: "Your wife is a teacher, right?",
    options: [
      "Your teacher is a doctor?",
      "Your wife is a teacher, right?",
      "She is a student.",
      "My sister is a teacher.",
    ],
    x: 200, y: 150, unit: 7,
  },
  {
    id: 'q153',
    type: 'translation',
    description: 'Kız kardeşin bir öğrenci, değil mi?',
    sentence: 'Kız kardeşin bir öğrenci, değil mi?',
    correctAnswer: "Your sister is a student, right?",
    options: [
      "My sister is a teacher, right?",
      "Your wife is a student, right?",
      "Your sister is a student, right?",
      "Is your sister a student?",
    ],
    x: 100, y: 250, unit: 7,
  },
  {
    id: 'q154',
    type: 'translation',
    description: 'Evet, annem bir doktor.',
    sentence: 'Evet, annem bir doktor.',
    correctAnswer: "Yes, my mom is a doctor.",
    options: [
      "No, my mom is a teacher.",
      "Yes, she is a doctor.",
      "Yes, my mom is a doctor.",
      "Yes, my wife is a doctor.",
    ],
    x: 200, y: 350, unit: 7,
  },
  {
    id: 'q155',
    type: 'translation',
    description: 'Cümleyi tamamlayın: Lisa is my ...',
    sentence: 'Lisa is my ...',
    correctAnswer: 'lawyer',
    options: ['milk', 'lawyer', 'Japan', 'Nice'],
    x: 100, y: 450, unit: 7,
  },
  {
    id: 'q156',
    type: 'matching',
    description: 'İngilizce kelimeleri Türkçe anlamlarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Doktor', 'Avukat', 'Öğrenci', 'Öğretmen'],
    rightOptions: ['Doctor', 'Lawyer', 'Student', 'Teacher'],
    correctPairs: [
      { left: 'Doktor', right: 'Doctor' },
      { left: 'Avukat', right: 'Lawyer' },
      { left: 'Öğrenci', right: 'Student' },
      { left: 'Öğretmen', right: 'Teacher' },
    ],
    x: 200, y: 550, unit: 7,
  },
  {
    id: 'q157',
    type: 'matching',
    description: 'İngilizce kelimeleri Türkçe anlamlarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Eş', 'Kız kardeş', 'Aşçı', 'Arkadaş'],
    rightOptions: ['Wife', 'Sister', 'Chef', 'Friend'],
    correctPairs: [
      { left: 'Eş', right: 'Wife' },
      { left: 'Kız kardeş', right: 'Sister' },
      { left: 'Aşçı', right: 'Chef' },
      { left: 'Arkadaş', right: 'Friend' },
    ],
    x: 100, y: 650, unit: 7,
  },
  {
    id: 'q158',
    type: 'matching',
    description: 'İngilizce kelimeleri Türkçe anlamlarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Annem', 'Hemşire', 'Ben de ...', 'Koca'],
    rightOptions: ['My mom', 'Nurse', "I'm ... too", 'Husband'],
    correctPairs: [
      { left: 'Annem', right: 'My mom' },
      { left: 'Hemşire', right: 'Nurse' },
      { left: 'Ben de ...', right: "I'm ... too" },
      { left: 'Koca', right: 'Husband' },
    ],
    x: 200, y: 750, unit: 7,
  },
  {
    id: 'q159',
    type: 'matching',
    description: 'İngilizce kelimeleri Türkçe anlamlarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Nerelisin?', 'O bir doktor', 'Evet', 'Hayır'],
    rightOptions: ['Where are you from?', 'She is a doctor', 'Yes', 'No'],
    correctPairs: [
      { left: 'Nerelisin?', right: 'Where are you from?' },
      { left: 'O bir doktor', right: 'She is a doctor' },
      { left: 'Evet', right: 'Yes' },
      { left: 'Hayır', right: 'No' },
    ],
    x: 100, y: 850, unit: 7,
  },
  {
    id: 'q160',
    type: 'matching',
    description: 'İngilizce kelimeleri Türkçe anlamlarıyla eşleştir',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Paris', 'Doktor', 'Öğretmen', 'Öğrenci'],
    rightOptions: ['Paris', 'Doctor', 'Teacher', 'Student'],
    correctPairs: [
      { left: 'Paris', right: 'Paris' },
      { left: 'Doktor', right: 'Doctor' },
      { left: 'Öğretmen', right: 'Teacher' },
      { left: 'Öğrenci', right: 'Student' },
    ],
    x: 200, y: 950, unit: 7,
  },  
  {
    id: 'q161',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: "I'm a doctor too",
    correctAnswer: "I'm a doctor too",
    options: [],
    words: ['I\'m', 'a', 'doctor', 'too', 'student', 'Lisa'],
    x: 100, y: 1050, unit: 7,
  },
  {
    id: 'q162',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: "Your sister is a student",
    correctAnswer: "Your sister is a student",
    options: [],
    words: ['Your', 'sister', 'is', 'a', 'student', 'chef'],
    x: 200, y: 1150, unit: 7,
  },
  {
    id: 'q163',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: "My friend is a doctor",
    correctAnswer: "My friend is a doctor",
    options: [],
    words: ['My', 'friend', 'is', 'a', 'doctor', 'lawyer'],
    x: 100, y: 1250, unit: 7,
  },
  {
    id: 'q164',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: "Is David a chef?",
    correctAnswer: "Is David a chef?",
    options: [],
    words: ['Is', 'David', 'a', 'chef', 'student', 'teacher'],
    x: 200, y: 1350, unit: 7,
  },
  {
    id: 'q165',
    type: 'listening',
    description: 'Dinleyin ve cümleyi oluşturun',
    sentence: "Lisa is my lawyer",
    correctAnswer: "Lisa is my lawyer",
    options: [],
    words: ['Lisa', 'is', 'my', 'lawyer', 'nurse', 'friend'],
    x: 100, y: 1450, unit: 7,
  },
  {
    id: 'q166',
    type: 'speaking',
    description: 'Cümleyi sesli tekrar edin: "I am a doctor."',
    sentence: "I am a doctor.",
    correctAnswer: "I am a doctor.",
    options: [],
    x: 200, y: 1550, unit: 7,
  },
  {
    id: 'q167',
    type: 'speaking',
    description: 'Cümleyi sesli tekrar edin: "Your sister is a student."',
    sentence: "Your sister is a student.",
    correctAnswer: "Your sister is a student.",
    options: [],
    x: 100, y: 1650, unit: 7,
  },
  {
    id: 'q168',
    type: 'speaking',
    description: 'Cümleyi sesli tekrar edin: "Lisa is a lawyer."',
    sentence: "Lisa is a lawyer.",
    correctAnswer: "Lisa is a lawyer.",
    options: [],
    x: 200, y: 1750, unit: 7,
  },
  {
    id: 'q169',
    type: 'speaking',
    description: 'Cümleyi sesli tekrar edin: "I am from Paris."',
    sentence: "I am from Paris.",
    correctAnswer: "I am from Paris.",
    options: [],
    x: 100, y: 1850, unit: 7,
  },
  {
    id: 'q170',
    type: 'speaking',
    description: 'Cümleyi sesli tekrar edin: "Yes, my mom is a doctor."',
    sentence: "Yes, my mom is a doctor.",
    correctAnswer: "Yes, my mom is a doctor.",
    options: [],
    x: 200, y: 1950, unit: 7,
  },
  {
    id: 'q171',
    type: 'imageChoice',
    description: 'Aşağıdaki kişilerden hangisi "doktor"?',
    sentence: 'doctor',
    correctAnswer: 'doctor',
    options: [],
    images: [
      { label: 'student', image: require('./assets/images/student.png') },
      { label: 'doctor', image: require('./assets/images/doctor.png') },
      { label: 'chef', image: require('./assets/images/chef.png') },
      { label: 'nurse', image: require('./assets/images/nurse.png') },
    ],
    x: 100, y: 2050, unit: 7,
  },
  {
    id: 'q172',
    type: 'imageChoice',
    description: 'Hangi görsel "aşçı" kelimesine aittir?',
    sentence: 'chef',
    correctAnswer: 'chef',
    options: [],
    images: [
      { label: 'doctor', image: require('./assets/images/doctor.png') },
      { label: 'lawyer', image: require('./assets/images/lawyer.png') },
      { label: 'chef', image: require('./assets/images/chef.png') },
      { label: 'student', image: require('./assets/images/student.png') },
    ],
    x: 200, y: 2150, unit: 7,
  },
  {
    id: 'q173',
    type: 'imageChoice',
    description: '"Öğrenci"yi gösteren görsel hangisidir?',
    sentence: 'student',
    correctAnswer: 'student',
    options: [],
    images: [
      { label: 'doctor', image: require('./assets/images/doctor.png') },
      { label: 'nurse', image: require('./assets/images/nurse.png') },
      { label: 'teacher', image: require('./assets/images/teacher.png') },
      { label: 'student', image: require('./assets/images/student.png') },
    ],
    x: 100, y: 2250, unit: 7,
  },
  {
    id: 'q174',
    type: 'imageChoice',
    description: '"Avukat" görselini seçin',
    sentence: 'lawyer',
    correctAnswer: 'lawyer',
    options: [],
    images: [
      { label: 'doctor', image: require('./assets/images/doctor.png') },
      { label: 'lawyer', image: require('./assets/images/lawyer.png') },
      { label: 'wife', image: require('./assets/images/wife.png') },
      { label: 'student', image: require('./assets/images/student.png') },
    ],
    x: 200, y: 2350, unit: 7,
  },
  {
    id: 'q175',
    type: 'imageChoice',
    description: '"Öğretmen"i gösteren resmi bulun',
    sentence: 'teacher',
    correctAnswer: 'teacher',
    options: [],
    images: [
      { label: 'teacher', image: require('./assets/images/teacher.png') },
      { label: 'nurse', image: require('./assets/images/nurse.png') },
      { label: 'husband', image: require('./assets/images/husband.png') },
      { label: 'student', image: require('./assets/images/student.png') },
    ],
    x: 100, y: 2450, unit: 7,
  },
  {
    id: 'q7e1',
    type: 'translation',
    description: 'Cümleyi doğru çevirin: "Ben doktorum, eşim ise bir öğretmen."',
    sentence: 'Ben doktorum, eşim ise bir öğretmen.',
    correctAnswer: 'I am a doctor, and my wife is a teacher.',
    options: [
      'I am a doctor, and my wife is a teacher.',
      'My teacher is a doctor and a wife.',
      'I am a student and my wife is a doctor.',
      'My wife is a lawyer, and I am a teacher.'
    ],
    x: 200,
    y: 2550,
    unit: 7,
    extra: true
  },
  {
    id: 'q7e2',
    type: 'matching',
    description: 'Meslekleri ve şehirlerle ilgili ifadeleri eşleştirin.',
    sentence: '',
    correctAnswer: '',
    options: [],
    leftOptions: ['Ben doktorum', 'Lisa bir avukat', 'Kocam bir aşçı', 'Annem Paris’te bir öğretmen'],
    rightOptions: [
      'I am a doctor',
      'Lisa is a lawyer',
      'My husband is a chef',
      'My mom is a teacher in Paris'
    ],
    correctPairs: [
      { left: 'Ben doktorum', right: 'I am a doctor' },
      { left: 'Lisa bir avukat', right: 'Lisa is a lawyer' },
      { left: 'Kocam bir aşçı', right: 'My husband is a chef' },
      { left: 'Annem Paris’te bir öğretmen', right: 'My mom is a teacher in Paris' }
    ],
    x: 100,
    y: 2650,
    unit: 7,
    extra: true
  },
  {
    id: 'q7e3',
    type: 'listening',
    description: 'Dinleyin ve doğru cümleyi oluşturun',
    sentence: 'My sister is a doctor and she works in London.',
    correctAnswer: 'My sister is a doctor and she works in London.',
    options: [],
    words: ['My', 'sister', 'is', 'a', 'doctor', 'and', 'she', 'works', 'in', 'London'],
    x: 200,
    y: 2750,
    unit: 7,
    extra: true
  },
  {
    id: 'q7e4',
    type: 'speaking',
    description: 'Bu cümleyi yüksek sesle söyleyin',
    sentence: 'My brother is a student, and my dad is a teacher.',
    correctAnswer: 'My brother is a student, and my dad is a teacher.',
    options: [],
    x: 100,
    y: 2850,
    unit: 7,
    extra: true
  },
  {
    id: 'q7e5',
    type: 'imageChoice',
    description: 'Aşağıdaki görsellerden hangisi "hemşire" mesleğine aittir?',
    sentence: 'nurse',
    correctAnswer: 'nurse',
    options: [],
    images: [
      { label: 'nurse', image: require('./assets/images/nurse.png') },
      { label: 'teacher', image: require('./assets/images/teacher.png') },
      { label: 'lawyer', image: require('./assets/images/lawyer.png') },
      { label: 'chef', image: require('./assets/images/chef.png') },
    ],
    x: 200,
    y: 2950,
    unit: 7,
    extra: true
  },
  
];
